<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Yoma
 * @package     Yoma_Realex
 * @copyright   Copyright (c) 2014 YOMA LIMITED (http://www.yoma.co.uk)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
    $_code = $this->getMethodCode();

    $tokenCards  = $this->getTokenCards();
    $cTokens  = ($tokenCards->getSize()>0 && $this->canUseToken());
    $realexStyle   = ($cTokens ? ' style=""' : '');
    $realexValidation   = ($cTokens ? ' realex-required-entry ' : ' realex-required-entry ');
?>

    <ul class="form-list paymentrealex" id="payment_form_<?php echo $_code ?>" style="display:none;">

        <?php if($this->canUseToken() && $this->canAddToken($tokenCards)): ?>

            <?php if($this->alwaysSave()): ?>
                <li<?php echo $realexStyle; ?>>
                    <label for="remembertoken-<?php echo $_code; ?>"><?php echo $this->__(mage::helper('realex')->getConfigData('realvault','auto_store_label')); ?></label>
                    <input type="hidden" name="payment[remembertoken]" value="1" id="remembertoken-<?php echo $_code; ?>" />
                </li>
            <?php else: ?>
                <li<?php echo $realexStyle; ?>>
                    <label for="remembertoken-<?php echo $_code; ?>"><?php echo $this->__(mage::helper('realex')->getConfigData('realvault','store_label')); ?></label>&nbsp;
                    <input checked="checked" type="checkbox" name="payment[remembertoken]" value="1" id="remembertoken-<?php echo $_code; ?>" />
                </li>
            <?php endif; ?>

        <?php endif; ?>
    </ul>

</ul>
