<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Yoma
 * @package     Yoma_Realex
 * @copyright   Copyright (c) 2014 YOMA LIMITED (http://www.yoma.co.uk)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
$cards = $this->getCustomerCards(); ?>
<div class="page-title">
	<h1>My Stored Cards</h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
<table class="data-table" id="realex-card-table">
    <thead>
        <tr>
            <th><?php echo $this->helper('realex')->__('Type') ?></th>
            <th><?php echo $this->helper('realex')->__('Number') ?></th>
            <th><?php echo $this->helper('realex')->__('Exp. Date') ?></th>
            <th class="a-center"><?php echo $this->helper('realex')->__('Default') ?></th>
            <th class="a-center" colspan="2"><?php echo $this->helper('realex')->__('Actions') ?></th>
        </tr>
    </thead>

    <tbody>
    	<?php if($cards->getSize()): ?>
    		<?php foreach($cards as $card): ?>
    		<tr>
    			<td><?php echo $this->getCcTypeName($card->getMagentoCardType(),$card->getPaymentCode()); ?></td>
    			<td><?php echo $card->getCcNumber(); ?></td>
    			<td><?php echo $card->getExpireDate(); ?></td>
    			<td class="a-center">
   					<input onclick="setDefault(this);" type="radio" name="tokencard_def" value="<?php echo $card->getId(); ?>"<?php if($card->checkCardDefault()): ?> checked="checked"<?php endif; ?> />
    			</td>
                <td class="a-center">
                    <a href="<?php echo $this->getUrl('realex/cards/edit/', array('card'=>$card->getId())) ?>"><?php echo $this->helper('realex')->__('Edit') ?></a>
                </td>
    			<td class="a-center">
                    <?php if($this->canDeleteCards()):?>
                        <a onclick="if(confirm('<?php echo $this->helper('realex')->__('Are you sure?'); ?>')){removeCard(this); return false; }else{return false;}" href="<?php echo $this->getUrl('realex/cards/delete/', array('card'=>$card->getId())) ?>"><?php echo $this->helper('realex')->__('Remove') ?></a>
                    <?php endif; ?>
                </td>
    		</tr>
    		<?php endforeach; ?>
		<?php else: ?>
		    <tr>
		        <td colspan="5" class="a-center"><p><?php echo $this->helper('realex')->__('You have no cards yet.') ?></p></td>
		    </tr>
		<?php endif; ?>
    </tbody>
</table>

<script type="text/javascript">decorateTable('realex-card-table');</script>
