<div style="text-align: center; margin-top: 150px;">

<h1>Thank you for signing up</h1>
<p>You will be redirected to your dashboard in 5 seconds...</p>

<!-- Google Code for Register /Contact /Buy Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 1039116083;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "4JttCPGJkQIQs86-7wM";
var google_conversion_value = 1.00;
var google_conversion_currency = "GBP";
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/1039116083/?value=1.00&amp;currency_code=GBP&amp;label=4JttCPGJkQIQs86-7wM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

	<?php $home_url = Mage::helper("core/url")->getHomeUrl(); ?>

<script>
	var myVar = setInterval(myTimer, 5000),
		url = '<?php echo $home_url; ?>/customer/account/';

	function myTimer() {
	    window.location.replace(url);
	}
</script>