<tr>
    <td class="label"><?php echo $this->helper('realex')->__('Settle Amount') ?>&nbsp;<input id="settle-check" type="checkbox" name="settle" value="0"></td>
    <td><input id="settle-amount" type="text" name="invoice[settle_positive]" value="" disabled="disabled" class="input-text not-negative-amount" style="width:60px;text-align:right;background-color: #AAAAAA" id="settle_positive"/></td>
</tr>