<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Yoma
 * @package     Yoma_Realex
 * @copyright   Copyright (c) 2014 YOMA LIMITED (http://www.yoma.co.uk)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
$card = $this->getCustomerCard();
$_code = 'realvault';
?>
<div class="page-title">
    <h1>Edit My Stored Cards</h1>
</div>
<form id="frmRegCard" action="<?php echo $this->getUrl('realex/cards/edit', array('card'=>$card->getId())); ?>" method="post">

	<ul class="form-list sp-methods" id="payment_form_<?php echo $_code ?>">
	    <li>
	        <label for="<?php echo $_code ?>_name" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
	        <div class="input-box">
	        	<input type="text" name="card_name" id="<?php echo $_code ?>_name" class="input-text required-entry" value="<?php echo $card->getChName(); ?>"/>
	        </div>
	    </li>

	    <li>
	        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
	        <div class="input-box">
	            <div class="v-fix">
	            	<select id="<?php echo $_code ?>_expiration" class="month required-entry" name="card_month">
						<?php echo $this->getMonthOptions(); ?>
					</select>
				</div>
				<div class="v-fix">
					<select id="<?php echo $_code ?>_expiration_year" class="year required-entry" name="card_year">
						<?php echo $this->getYearOptions(); ?>
					</select>
	            </div>
	        </div>
	    </li>

	    <li id="<?php echo $_code ?>_cc_post">
	        <div class="input-box">
	            <div class="v-fix">
	                <button type="submit" class="button" title="<?php echo $this->__('Update Card'); ?>">
                        <span>
                        	<span>
                        		<?php echo $this->__('Update Card'); ?>
                        	</span>
                        </span>
                    </button>
	            </div>
	        </div>
	    </li>
	</ul>

</form>