<section class="custom-contact-form">
    <div id="messages_product_view">
        <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
        <?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
        <?php echo $this->getMessagesBlock()->toHtml() ?>
    </div>
    <div class="page-title">
        <h3><?php echo Mage::helper('contacts')->__('Contact Us') ?></h3>
    </div>


    <form action="<?php echo Mage::getUrl('contacts/index/post'); ?>" id="contactForm" method="post">
        <div class="fieldset">
            <h2 class="legend"><?php echo Mage::helper('contacts')->__('Contact Information') ?></h2>
            <p>Complete the form below and we’ll get back to you. </p>
            <p>Fields marked with an asterisk are mandatory</p>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <select class="select-style" name="about-us-list" form="contactForm">
                            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('contact_about_dropdown')->toHtml() ?>
                        </select>
                    </div>
                </li>
                <input type="hidden" id="query" name="query" value="">
                <li class="fields">
                    <div class="field query-field" style="display: none;">
                        <label for="name"><?php echo Mage::helper('contacts')->__('Query') ?></label>
                        <div class="input-box">
                            <input name="about_query" id="about_query" value="" class="input-text required-entry" type="text"/>
                        </div>
                    </div>                    
                    <div class="field">
                        <label for="name" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Name') ?></label>
                        <div class="input-box">
                            <input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="email" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Email') ?></label>
                        <div class="input-box">
                            <input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                        </div>
                    </div>                    
                </li>
                <li>
                    <label class="required" for="telephone"><?php echo Mage::helper('contacts')->__('Telephone') ?></label>
                    <div class="input-box">
                        <input name="telephone" id="telephone" title="<?php echo Mage::helper('contacts')->__('Telephone') ?>" value="" class="input-text required-entry" type="text" />
                    </div>
                </li>
                <li class="wide">
                    <label for="comment" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Comment') ?></label>
                    <div class="input-box">
                        <textarea name="comment" id="comment" title="<?php echo Mage::helper('contacts')->__('Comment') ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                    </div>
                </li>
            </ul>
        </div>
        <div class="buttons-set">
            <p class="required"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
            <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
            <button type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
        </div>
    </form>
    <script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion_async.js" charset="utf-8"></script>

    <script type="text/javascript">
    //<![CDATA[
        var contactForm = new VarienForm('contactForm', false);
    //]]>

    if ( jQuery( "#messages_product_view2 .notice-msg" ).length ) {
     
        jQuery( "#messages_product_view2 .notice-msg" ).css('display', 'none');

        /* <![CDATA[ */
        window.google_trackConversion({
          google_conversion_id: 1039116083,
          google_conversion_language: "en",
          google_conversion_format: "3",
          google_conversion_color: "ffffff",
          google_conversion_label: "_fl3CMPMvAEQs86-7wM",
          google_conversion_value: 1.00,
          google_conversion_currency: "GBP",
          google_remarketing_only: false,          
          google_remarketing_only: true
        });
        //]]>        

    }
    </script>
</section>