<section class="custom-contact-form">
    <div id="messages_product_view">
        <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
        <?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
        <?php echo $this->getMessagesBlock()->toHtml() ?>
    </div>
    <div class="page-title">
        <h3><?php echo Mage::helper('contacts')->__('Contact Us') ?></h3>
    </div>

    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('contact_form_block'); ?>

    <script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion_async.js" charset="utf-8"></script>

    <script type="text/javascript">
    //<![CDATA[
        var contactForm = new VarienForm('contactForm', false);
    //]]>

    if ( jQuery( "#messages_product_view2 .notice-msg" ).length ) {
     
        jQuery( "#messages_product_view2 .notice-msg" ).css('display', 'none');

        /* <![CDATA[ */
        window.google_trackConversion({
          google_conversion_id: 1039116083,
          google_conversion_language: "en",
          google_conversion_format: "3",
          google_conversion_color: "ffffff",
          google_conversion_label: "_fl3CMPMvAEQs86-7wM",
          google_conversion_value: 1.00,
          google_conversion_currency: "GBP",
          google_remarketing_only: false,          
          google_remarketing_only: true
        });
        //]]>        

    }
    </script>
</section>